FROM container.repository.cloudera.com/cloudera/flink:1.19.1-csaop1.1.2-b17
# To build this example without a Cloudera license, please switch to the Apache docker image:
#FROM flink:1.19

COPY ./target/flink-kubernetes-tutorial*.jar /opt/flink/usrlib/flink-kubernetes-tutorial.jar
