FROM container.repository.cloudera.com/cloudera/flink:1.19.2-csaop1.2.0-b27
# To build this example without a Cloudera license, please switch to the Apache docker image:
#FROM flink:1.19

COPY ./target/flink-kubernetes-tutorial*.jar /opt/flink/usrlib/flink-kubernetes-tutorial.jar
