FROM container.repository.cloudera.com/cloudera/flink:1.20.1-csaop1.5.0-b100
# To build this example without a Cloudera license, please switch to the Apache docker image:
#FROM flink:1.20

COPY ./target/flink-kubernetes-tutorial*.jar /opt/flink/usrlib/flink-kubernetes-tutorial.jar
